# Generated by Django 4.1.3 on 2022-12-06 08:55

from django.db import migrations, models
import django.db.models.deletion
import excursions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=excursions.models.photo_file_name)),
                ('excursion_map', models.FileField(blank=True, null=True, upload_to=excursions.models.map_file_name)),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='ExcursionPointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.FileField(blank=True, null=True, upload_to=excursions.models.content_excursion_name)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Точка галереи',
                'verbose_name_plural': 'Точки галереи',
            },
        ),
        migrations.CreateModel(
            name='ExcursionPhoneCodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('random_cod', models.IntegerField()),
                ('excursions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursionmodel')),
            ],
            options={
                'verbose_name': 'Код для сверки',
                'verbose_name_plural': 'Коды для сверки',
            },
        ),
        migrations.AddField(
            model_name='excursionmodel',
            name='point',
            field=models.ManyToManyField(to='excursions.excursionpointmodel'),
        ),
    ]
