# Generated by Django 4.1.3 on 2022-12-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursions', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenExModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('body', models.CharField(max_length=20)),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('date_activate', models.DateTimeField(blank=True, null=True)),
                ('driver_activate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivermodel')),
                ('excursion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursionmodel')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
    ]
